### PR TITLE
add an alternative logic

### PR DESCRIPTION
**Pull request by zcsahok**
(will add description later)

### CODE REVIEW

**Comment by airween** [comment]
Thank you Zoli, you convinced me :).

**Comment by zcsahok** [comment]
The goal is to make clear on the air what is actually confirmed.
The logic is as follows:

- calls are split into 5 parts: alt-prefix, prefix, area, suffix, alt-area. The alt-x parts are optional.
- if one of these or two consecutive change, then send it/them. Always send a changed part fully.
- always send at least 2 chars. If needed pad from a neighboring field.
- if more than two or non consecutive parts change, then send full call.
- some special handling is added for the optional alt-x parts, as they can either appear or get removed.

Added a bunch of examples to see how it behaves. The trailing `*` shows that the result is different from the original algorithm.

**Comment by airween** [comment]
Hi Zoli,

> The goal is to make clear on the air what is actually confirmed. The logic is as follows:
> 
>     * calls are split into 5 parts: alt-prefix, prefix, area, suffix, alt-area. The alt-x parts are optional.
>     * if one of these or two consecutive change, then send it/them. Always send a changed part fully.
>     * always send at least 2 chars. If needed pad from a neighboring field.
>     * if more than two or non consecutive parts change, then send full call.
>     * some special handling is added for the optional alt-x parts, as they can either appear or get removed.

yes, I reviewed the code and understood completely. Nice idea and nice solution, congrats!
 
> Added a bunch of examples to see how it behaves. The trailing `*` shows that the result is different from the original algorithm.

yes, that was clear for me too. I added yet another example in the comment under the original PR, just check how the function behaviors with a single shorter call.

Thanks for all, I'll update my PR soon, considering your other comments too.

**Comment by zcsahok** [comment]
OK. I'll still rework it a bit, introducing a struct for the split call parts. But that I can add to the other PR directly, too.

**Comment by airween** [comment]
Thanks Zoli, I'm going to merge it, and replace my PR under the [tlf](https://github.com/Tlf/tlf/pull/322) too.

**Pull request merged**
